import Head from 'next/head'
import Image from 'next/image'
import { useState } from 'react'
import Link from "next/link"

const Home = ({ location }) => {
    const [name, setName] = useState('')
    const [room, setRoom] = useState('')
        return (
      <div className="flex flex-col w-screen h-screen relative bg-teal-100 overflow-x-hidden">
        <Head>
          <title>Realtime Chat Application</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
          <main className="flex flex-col lg:px-20 mt-8 relative">
          
            <form action="" className="flex flex-col space-y-3 p-4 bg-white rounded-md shadow-md shadow-gray-100 absolute top-1/2 left-1/2 -translate-x-1/2 translate-y-1/2">
              <h4 className="text-gray-800 text-xl font-serif my-4">Start/Join a Chat</h4>
              <input onChange={event => setName(event.target.value)} type="text" name="" id="" className="text-sm text-gray-600 h-10 border border-gray-400 focus:border-yellow-400 focus:outline-none bg-transparent p-2" placeholder="Enter Your Name"/>
              <input onChange={event => setRoom(event.target.value)} type="text" name="" id="" className="text-sm text-gray-600 h-10 border border-gray-400 focus:border-yellow-400 focus:outline-none bg-transparent p-2" placeholder="Enter Chat Title" />
                <Link passHref href={ `/meeting?name=${name}&room=${room}`}>
                  <button onClick={(event) => (!name || !room) ? event.preventDefault() : null} type="submit" className="p-3 bg-teal-300 text-gray-800 text-sm font-normal">Chat</button>
                </Link>
            </form>
        </main>
      </div>
    )
}
  export default Home